Traceback (most recent call last):
  File "udr_ole.py", line 101, in <module>
    main()
  File "udr_ole.py", line 95, in main
    train_test(args, train_env, test_env, w)
  File "udr_ole.py", line 65, in train_test
    model.learn(total_timesteps=2e3, reset_num_timesteps=False,
callback=custom_callback, progress_bar=True)
  File
"/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/stable_baselines3/p
po/ppo.py", line 313, in learn
    progress_bar=progress_bar,
  File
"/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/stable_baselines3/c
ommon/on_policy_algorithm.py", line 248, in learn
    continue_training = self.collect_rollouts(self.env, callback,
self.rollout_buffer, n_rollout_steps=self.n_steps)
  File
"/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/stable_baselines3/c
ommon/on_policy_algorithm.py", line 181, in collect_rollouts
    if callback.on_step() is False:
  File
"/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/stable_baselines3/c
ommon/callbacks.py", line 100, in on_step
    return self._on_step()
  File
"/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/stable_baselines3/c
ommon/callbacks.py", line 204, in _on_step
    continue_training = callback.on_step() and continue_training
  File
"/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/stable_baselines3/c
ommon/callbacks.py", line 97, in on_step
    self.n_calls += 1
AttributeError: 'myCallback' object has no attribute 'n_calls'
[35m   0%[39m [38m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[39m [32m0/2,000 [39m [ [33m0:00:00[39m < [36m-:--:--[39m , [31m? it/s[39m ]