2024-07-10 16:12:45,912 INFO    StreamThr :76370 [internal.py:wandb_internal():88] W&B internal server running at pid: 76370, started at: 2024-07-10 16:12:45.912527
2024-07-10 16:12:45,913 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: status
2024-07-10 16:12:45,919 INFO    WriterThread:76370 [datastore.py:open_for_write():87] open: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/run-ispsviyr.wandb
2024-07-10 16:12:45,919 DEBUG   SenderThread:76370 [sender.py:send():379] send: header
2024-07-10 16:12:45,920 DEBUG   SenderThread:76370 [sender.py:send():379] send: run
2024-07-10 16:12:46,457 INFO    SenderThread:76370 [dir_watcher.py:__init__():211] watching files in: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files
2024-07-10 16:12:46,457 INFO    SenderThread:76370 [sender.py:_start_run_threads():1191] run started: ispsviyr with start time 1720620765.911859
2024-07-10 16:12:46,464 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: check_version
2024-07-10 16:12:46,464 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: check_version
2024-07-10 16:12:46,550 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: run_start
2024-07-10 16:12:46,550 DEBUG   HandlerThread:76370 [system_info.py:__init__():26] System info init
2024-07-10 16:12:46,551 DEBUG   HandlerThread:76370 [system_info.py:__init__():41] System info init done
2024-07-10 16:12:46,551 INFO    HandlerThread:76370 [system_monitor.py:start():194] Starting system monitor
2024-07-10 16:12:46,551 INFO    SystemMonitor:76370 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-07-10 16:12:46,551 INFO    HandlerThread:76370 [system_monitor.py:probe():214] Collecting system info
2024-07-10 16:12:46,552 INFO    SystemMonitor:76370 [interfaces.py:start():188] Started cpu monitoring
2024-07-10 16:12:46,553 INFO    SystemMonitor:76370 [interfaces.py:start():188] Started disk monitoring
2024-07-10 16:12:46,553 INFO    SystemMonitor:76370 [interfaces.py:start():188] Started memory monitoring
2024-07-10 16:12:46,554 INFO    SystemMonitor:76370 [interfaces.py:start():188] Started network monitoring
2024-07-10 16:12:46,558 DEBUG   HandlerThread:76370 [system_info.py:probe():152] Probing system
2024-07-10 16:12:46,562 DEBUG   HandlerThread:76370 [gitlib.py:_init_repo():56] git repository is invalid
2024-07-10 16:12:46,562 DEBUG   HandlerThread:76370 [system_info.py:probe():200] Probing system done
2024-07-10 16:12:46,562 DEBUG   HandlerThread:76370 [system_monitor.py:probe():223] {'os': 'Linux-6.8.0-36-generic-x86_64-with-debian-trixie-sid', 'python': '3.7.12', 'heartbeatAt': '2024-07-10T14:12:46.558322', 'startedAt': '2024-07-10T14:12:45.899680', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'train_sb3_tuning.py', 'codePathLocal': 'train_sb3_tuning.py', 'codePath': 'train_sb3_tuning.py', 'host': 'chiara-ASUS-EXPERTBOOK-B3402FEA-B3402FEA', 'username': 'chiar', 'executable': '/home/chiar/anaconda3/envs/mldl/bin/python', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2887.534, 'min': 400.0, 'max': 4700.0}, 'cpu_freq_per_core': [{'current': 4109.879, 'min': 400.0, 'max': 4700.0}, {'current': 4099.957, 'min': 400.0, 'max': 4700.0}, {'current': 1531.129, 'min': 400.0, 'max': 4700.0}, {'current': 2590.324, 'min': 400.0, 'max': 4700.0}, {'current': 4099.946, 'min': 400.0, 'max': 4700.0}, {'current': 4100.0, 'min': 400.0, 'max': 4700.0}, {'current': 400.583, 'min': 400.0, 'max': 4700.0}, {'current': 2282.181, 'min': 400.0, 'max': 4700.0}], 'disk': {'/': {'total': 265.1777763366699, 'used': 37.83089828491211}}, 'memory': {'total': 23.171894073486328}}
2024-07-10 16:12:46,562 INFO    HandlerThread:76370 [system_monitor.py:probe():224] Finished collecting system info
2024-07-10 16:12:46,562 INFO    HandlerThread:76370 [system_monitor.py:probe():227] Publishing system info
2024-07-10 16:12:46,563 DEBUG   HandlerThread:76370 [system_info.py:_save_conda():210] Saving list of conda packages installed into the current environment
2024-07-10 16:12:47,458 INFO    Thread-12 :76370 [dir_watcher.py:_on_file_created():271] file/dir created: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files/conda-environment.yaml
2024-07-10 16:12:47,882 DEBUG   HandlerThread:76370 [system_info.py:_save_conda():224] Saving conda packages done
2024-07-10 16:12:47,883 INFO    HandlerThread:76370 [system_monitor.py:probe():229] Finished publishing system info
2024-07-10 16:12:47,894 DEBUG   SenderThread:76370 [sender.py:send():379] send: files
2024-07-10 16:12:47,894 INFO    SenderThread:76370 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-07-10 16:12:47,935 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: python_packages
2024-07-10 16:12:47,935 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: python_packages
2024-07-10 16:12:47,936 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: stop_status
2024-07-10 16:12:47,936 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: stop_status
2024-07-10 16:12:47,976 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-10 16:12:48,182 ERROR   wandb-upload_0:76370 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-07-10 16:12:48,182 ERROR   wandb-upload_0:76370 [internal_api.py:execute():350] {"errors":[{"message":"run target-target-callback/ispsviyr not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-07-10 16:12:48,182 ERROR   Thread-11 :76370 [step_upload.py:_handle_event():145] Failed to upload file: /tmp/tmpf2qbjcizwandb/c2h0puca-wandb-metadata.json
Traceback (most recent call last):
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 2506, in upload_urls
    "files": [file for file in files],
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 320, in gql
    **kwargs,
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/util.py", line 911, in no_retry_auth
    "It appears that you do not have permission to access the requested resource. "
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-10 16:12:48,240 DEBUG   SenderThread:76370 [sender.py:send():379] send: telemetry
2024-07-10 16:12:48,457 INFO    Thread-12 :76370 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files/conda-environment.yaml
2024-07-10 16:12:48,458 INFO    Thread-12 :76370 [dir_watcher.py:_on_file_created():271] file/dir created: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files/output.log
2024-07-10 16:12:48,458 INFO    Thread-12 :76370 [dir_watcher.py:_on_file_created():271] file/dir created: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files/requirements.txt
2024-07-10 16:12:48,458 INFO    Thread-12 :76370 [dir_watcher.py:_on_file_created():271] file/dir created: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files/wandb-metadata.json
2024-07-10 16:12:48,936 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-10 16:12:49,936 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-10 16:12:50,454 ERROR   FileStreamThread:76370 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/poli_to/target-target-callback/ispsviyr/file_stream
NoneType: None
2024-07-10 16:12:50,458 INFO    Thread-12 :76370 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files/output.log
2024-07-10 16:12:50,936 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-10 16:12:51,017 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: status_report
2024-07-10 16:12:51,852 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: partial_history
2024-07-10 16:12:51,854 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: server_info
2024-07-10 16:12:51,854 DEBUG   SenderThread:76370 [sender.py:send():379] send: history
2024-07-10 16:12:51,854 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: summary_record
2024-07-10 16:12:51,854 INFO    SenderThread:76370 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-10 16:12:51,854 DEBUG   SenderThread:76370 [sender.py:send():379] send: telemetry
2024-07-10 16:12:51,855 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: server_info
2024-07-10 16:12:52,011 DEBUG   SenderThread:76370 [sender.py:send():379] send: exit
2024-07-10 16:12:52,011 INFO    SenderThread:76370 [sender.py:send_exit():586] handling exit code: 0
2024-07-10 16:12:52,012 INFO    SenderThread:76370 [sender.py:send_exit():588] handling runtime: 5
2024-07-10 16:12:52,012 INFO    SenderThread:76370 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-10 16:12:52,013 INFO    SenderThread:76370 [sender.py:send_exit():594] send defer
2024-07-10 16:12:52,013 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: defer
2024-07-10 16:12:52,013 INFO    HandlerThread:76370 [handler.py:handle_request_defer():184] handle defer: 0
2024-07-10 16:12:52,014 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: defer
2024-07-10 16:12:52,014 INFO    SenderThread:76370 [sender.py:send_request_defer():610] handle sender defer: 0
2024-07-10 16:12:52,014 INFO    SenderThread:76370 [sender.py:transition_state():614] send defer: 1
2024-07-10 16:12:52,014 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: defer
2024-07-10 16:12:52,014 INFO    HandlerThread:76370 [handler.py:handle_request_defer():184] handle defer: 1
2024-07-10 16:12:52,015 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: defer
2024-07-10 16:12:52,015 INFO    SenderThread:76370 [sender.py:send_request_defer():610] handle sender defer: 1
2024-07-10 16:12:52,015 INFO    SenderThread:76370 [sender.py:transition_state():614] send defer: 2
2024-07-10 16:12:52,015 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: defer
2024-07-10 16:12:52,015 INFO    HandlerThread:76370 [handler.py:handle_request_defer():184] handle defer: 2
2024-07-10 16:12:52,015 INFO    HandlerThread:76370 [system_monitor.py:finish():203] Stopping system monitor
2024-07-10 16:12:52,015 DEBUG   SystemMonitor:76370 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-07-10 16:12:52,016 DEBUG   SystemMonitor:76370 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-07-10 16:12:52,016 DEBUG   SystemMonitor:76370 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-07-10 16:12:52,017 INFO    HandlerThread:76370 [interfaces.py:finish():200] Joined cpu monitor
2024-07-10 16:12:52,017 INFO    HandlerThread:76370 [interfaces.py:finish():200] Joined disk monitor
2024-07-10 16:12:52,017 INFO    HandlerThread:76370 [interfaces.py:finish():200] Joined memory monitor
2024-07-10 16:12:52,017 INFO    HandlerThread:76370 [interfaces.py:finish():200] Joined network monitor
2024-07-10 16:12:52,018 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: defer
2024-07-10 16:12:52,018 INFO    SenderThread:76370 [sender.py:send_request_defer():610] handle sender defer: 2
2024-07-10 16:12:52,018 INFO    SenderThread:76370 [sender.py:transition_state():614] send defer: 3
2024-07-10 16:12:52,018 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: defer
2024-07-10 16:12:52,018 INFO    HandlerThread:76370 [handler.py:handle_request_defer():184] handle defer: 3
2024-07-10 16:12:52,019 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: defer
2024-07-10 16:12:52,019 INFO    SenderThread:76370 [sender.py:send_request_defer():610] handle sender defer: 3
2024-07-10 16:12:52,019 INFO    SenderThread:76370 [sender.py:transition_state():614] send defer: 4
2024-07-10 16:12:52,019 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: defer
2024-07-10 16:12:52,019 INFO    HandlerThread:76370 [handler.py:handle_request_defer():184] handle defer: 4
2024-07-10 16:12:52,020 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: defer
2024-07-10 16:12:52,020 INFO    SenderThread:76370 [sender.py:send_request_defer():610] handle sender defer: 4
2024-07-10 16:12:52,020 INFO    SenderThread:76370 [sender.py:transition_state():614] send defer: 5
2024-07-10 16:12:52,020 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: defer
2024-07-10 16:12:52,020 INFO    HandlerThread:76370 [handler.py:handle_request_defer():184] handle defer: 5
2024-07-10 16:12:52,021 DEBUG   SenderThread:76370 [sender.py:send():379] send: summary
2024-07-10 16:12:52,021 INFO    SenderThread:76370 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-10 16:12:52,022 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: defer
2024-07-10 16:12:52,022 INFO    SenderThread:76370 [sender.py:send_request_defer():610] handle sender defer: 5
2024-07-10 16:12:52,022 INFO    SenderThread:76370 [sender.py:transition_state():614] send defer: 6
2024-07-10 16:12:52,022 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: defer
2024-07-10 16:12:52,022 INFO    HandlerThread:76370 [handler.py:handle_request_defer():184] handle defer: 6
2024-07-10 16:12:52,023 DEBUG   SenderThread:76370 [sender.py:send_request():406] send_request: defer
2024-07-10 16:12:52,023 INFO    SenderThread:76370 [sender.py:send_request_defer():610] handle sender defer: 6
2024-07-10 16:12:52,028 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: status_report
2024-07-10 16:12:52,182 ERROR   SenderThread:76370 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-07-10 16:12:52,182 ERROR   SenderThread:76370 [internal_api.py:execute():350] {"errors":[{"message":"run ispsviyr was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-07-10 16:12:52,397 ERROR   FileStreamThread:76370 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/poli_to/target-target-callback/ispsviyr/file_stream
NoneType: None
2024-07-10 16:12:52,459 INFO    Thread-12 :76370 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files/output.log
2024-07-10 16:12:52,459 INFO    Thread-12 :76370 [dir_watcher.py:_on_file_created():271] file/dir created: /home/chiar/mldl-main/wandb/run-20240710_161245-ispsviyr/files/wandb-summary.json
2024-07-10 16:12:53,011 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-10 16:12:53,392 ERROR   SenderThread:76370 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-07-10 16:12:53,392 ERROR   SenderThread:76370 [internal_api.py:execute():350] {"errors":[{"message":"run ispsviyr was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-07-10 16:12:55,883 ERROR   SenderThread:76370 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-07-10 16:12:55,883 ERROR   SenderThread:76370 [internal_api.py:execute():350] {"errors":[{"message":"run ispsviyr was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-07-10 16:12:55,883 INFO    SenderThread:76370 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/chiar/anaconda3/envs/mldl/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-07-10 16:12:58,013 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: keepalive
2024-07-10 16:13:00,412 ERROR   SenderThread:76370 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-07-10 16:13:00,412 ERROR   SenderThread:76370 [internal_api.py:execute():350] {"errors":[{"message":"run ispsviyr was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-07-10 16:13:03,013 DEBUG   HandlerThread:76370 [handler.py:handle_request():158] handle_request: keepalive
2024-07-10 16:13:10,442 ERROR   SenderThread:76370 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-07-10 16:13:10,442 ERROR   SenderThread:76370 [internal_api.py:execute():350] {"errors":[{"message":"run ispsviyr was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-07-10 16:13:20,559 INFO    MainThread:76370 [internal.py:handle_exit():75] Internal process exited
